#ifndef BARESIP_DIALOG_INFO_DIRECTION
#define BARESIP_DIALOG_INFO_DIRECTION

enum dialog_info_direction {
	DIALOG_INFO_DIR_UNKNOWN = 0,
	DIALOG_INFO_DIR_INITIATOR,
	DIALOG_INFO_DIR_RECIPIENT
};

#endif
