//---------------------------------------------------------------------------

#pragma hdrstop

#include "LuaHtmlExportCommon.h"
#include "Branding.h"
#include "common/Utilities.h"
#include "baresip_base_config.h"
#include <Forms.hpp>

//---------------------------------------------------------------------------

#pragma package(smart_init)

AnsiString LuaHtmlExportCommon::HtmlEscape(AnsiString text)
{
	AnsiString result;
	for (int i = 1; i <= text.Length(); i++)
	{
		switch (text[i])
		{
		case '&': result += "&amp;"; break;
		case '<': result += "&lt;"; break;
		case '>': result += "&gt;"; break;
		case '"': result += "&quot;"; break;
		default: result += text[i]; break;
		}
	}
	return result;
}

AnsiString LuaHtmlExportCommon::PrepareText(AnsiString text)
{
	return AnsiToUtf8(HtmlEscape(text));
}

AnsiString LuaHtmlExportCommon::GetGeneratedByLine(void)
{
	AnsiString version = GetFileVer(Application->ExeName);
	AnsiString buildTimestamp = (AnsiString)__DATE__ + ", " __TIME__;
#ifdef USE_VIDEO
	bool videoSupport = true;
#else
	bool videoSupport = false;
#endif
	AnsiString generatedBy;
	generatedBy.sprintf("Generated by %s %s, built %s (%s video support)",
		Branding::appName.c_str(), version.c_str(), buildTimestamp.c_str(), videoSupport ? "with" : "without");
	return PrepareText(generatedBy);
}
