//---------------------------------------------------------------------------

#ifndef LuaHtmlExportCommonH
#define LuaHtmlExportCommonH
//---------------------------------------------------------------------------

#include <System.hpp>

/** \brief Bits shared by the various "export Lua-related info to HTML" features
	(custom functions list, built-in examples list, ...): HTML-escaping, ANSI to
	UTF-8 conversion and the "Generated by <app> <version>, built <timestamp>
	(with/without video support)" line.
*/
namespace LuaHtmlExportCommon
{
	AnsiString HtmlEscape(AnsiString text);

	/** \brief HTML-escape text and convert it from the local ANSI code page to UTF-8 */
	AnsiString PrepareText(AnsiString text);

	/** \brief HTML-escaped, UTF-8 "Generated by ..." line describing the running executable */
	AnsiString GetGeneratedByLine(void);
}

#endif
